sudo: false
language: java

env:
  global:

matrix:
  allow_failures:
    - name: Test with OpenJDK 11
  include:
    - name: Test with OpenJDK 11
      jdk: openjdk11
      script: mvn -DskipTests=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean install
    - name: Test with Oracle jdk8
      jdk: oraclejdk8
      script: mvn -DskipTests=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean install
